# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
